#!/bin/sh

./init-db

# add-apt-repository -y ppa:webupd8team/java
# apt-get update
# apt-get install -y python-software-properties
# apt-get install -y tomcat7-user

tomcat7-instance-create dhis2-server
unzip -o dhis.war -d dhis2-server/webapps/dhis2
